(function (global) {
  global.urlParams = new URLSearchParams(window.location.search);
  global.defaultBridgeUrl = "http://127.0.0.1:8765";
  global.storageHelpers = window.FlatShotStorage;
  global.numberHelpers = window.FlatShotNumberUtils;
  global.bridgeUrlHelpers = window.FlatShotBridgeUrl;
  global.bridgeClientHelpers = window.FlatShotBridgeClient;
  global.actionHandlerHelpers = window.FlatShotActionHandlers;
  global.interactionBindingHelpers = window.FlatShotInteractionBindings;
  global.sessionSnapshotHelpers = window.FlatShotSessionSnapshot;
  global.backgroundPresetHelpers = window.FlatShotBackgroundPresets;
  global.appStateHelpers = window.FlatShotAppState;
  global.initialBridgeUrl = global.bridgeUrlHelpers.initialBridgeUrlFromSearch(window.location.search, global.defaultBridgeUrl);
  global.devMode = global.urlParams.get("dev") === "1";
  global.SOFT_BLACK_PREVIEW_BG = "soft-black";
  global.DEFAULT_PREVIEW_CUSTOM_RGB = [230, 230, 230];
  global.formatterHelpers = window.FlatShotFormatters;
  global.outputProfileHelpers = window.FlatShotOutputProfiles;
  global.outputProfileViewHelpers = window.FlatShotOutputProfileView;
  global.exportPayloadHelpers = window.FlatShotExportPayload;
  global.exportStateHelpers = window.FlatShotExportState;
  global.exportSummaryViewHelpers = window.FlatShotExportSummaryView;
  global.exportResultViewHelpers = window.FlatShotExportResultView;
  global.exportPreflightViewHelpers = window.FlatShotExportPreflightView;
  global.topStatusViewHelpers = window.FlatShotTopStatusView;
  global.preflightHelpers = window.FlatShotPreflight;
  global.batchViewHelpers = window.FlatShotBatchView;
  global.scanStateHelpers = window.FlatShotScanState;
  global.exportConfirmViewHelpers = window.FlatShotExportConfirmView;
  global.emptyStateViewHelpers = window.FlatShotEmptyStateView;
  global.batchDetailViewHelpers = window.FlatShotBatchDetailView;
  global.galleryHelpers = window.FlatShotGallery;
  global.previewViewHelpers = window.FlatShotPreviewView;
  global.previewStateHelpers = window.FlatShotPreviewState;
  global.settingsViewHelpers = window.FlatShotSettingsView;
  global.inspectorOutputViewHelpers = window.FlatShotInspectorOutputView;
  global.inspectorReviewViewHelpers = window.FlatShotInspectorReviewView;
  global.inspectorContextViewHelpers = window.FlatShotInspectorContextView;

  document.documentElement.classList.toggle("dev-mode", global.devMode);
})(typeof window !== "undefined" ? window : globalThis);
